import plugin from 'tailwindcss/plugin';

export default plugin(({ addComponents, theme }) => {
  addComponents({
    '.typography-h1': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '94px',
      letterSpacing: '-1.5px',
    },
    '.typography-h2': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '59px',
      letterSpacing: '0.5px',
    },
    '.typography-h3': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '47px',
      letterSpacing: '0px',
    },
    '.typography-h4': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '33px',
      letterSpacing: '0.25px',
    },
    '.typography-h5': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '24px',
      letterSpacing: '0px',
    },
    '.typography-h6': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '20px',
      letterSpacing: '0.15px',
    },
    '.typography-h7': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '18px',
      lineHeight: '22.5px',
      letterSpacing: '0.1px',
    },
    '.typography-st1': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '16px',
      letterSpacing: '0.15px',
    },
    '.typography-st2': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '14px',
      letterSpacing: '0.1px',
    },
    '.typography-b1': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '500',
      fontSize: '16px',
      letterSpacing: '0.5px',
    },
    '.typography-b2': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '500',
      lineHeight: '17.5px',
      fontSize: '14px',
      letterSpacing: '0.25px',
    },
    '.typography-b3': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '500',
      lineHeight: '15px',
      fontSize: '12px',
      letterSpacing: '0.25px',
    },
    '.typography-button1': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '16px',
      letterSpacing: '1.25px',
    },
    '.typography-button2': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '14px',
      letterSpacing: '1.25px',
    },
    '.typography-button3': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '600',
      fontSize: '12px',
      letterSpacing: '1px',
    },
    '.typography-link1': {
      fontFamily: theme('fontFamily.f1'),
      fontSize: '1rem',
      fontStyle: 'normal',
      fontWeight: '600',
      lineHeight: 'normal',
      letterSpacing: '0.03125rem',
      textDecorationLine: 'underline',
    },
    '.typography-link2': {
      fontFamily: theme('fontFamily.f1'),
      fontSize: '0.875rem',
      fontStyle: 'normal',
      fontWeight: '600',
      lineHeight: 'normal',
      letterSpacing: '0.03125rem',
      textDecorationLine: 'underline',
    },
    '.typography-link3': {
      fontFamily: theme('fontFamily.f1'),
      fontSize: '0.75rem',
      fontStyle: 'normal',
      fontWeight: '600',
      lineHeight: 'normal',
      letterSpacing: '0.03125rem',
      textDecorationLine: 'underline',
    },
    '.typography-caption': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '500',
      fontSize: '12px',
      letterSpacing: '0.4px',
    },
    '.typography-hint': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '500',
      fontSize: '10px',
      letterSpacing: '0.4px',
    },
    '.typography-overline': {
      fontFamily: theme('fontFamily.f1'),
      fontWeight: '500',
      fontSize: '10px',
      letterSpacing: '1.5px',
    },
  });
});
