// Definir los tipos aquí para evitar dependencia circular
export type IconSet = 'hi' | 'md' | 'fa' | 'ri' | 'bi' | 'ai' | 'bs' | 'tb' | 'gi' | 'wi' | 'di' | 'si' | 'im' | 'fi' | 'cg' | 'vsc' | 'go' | 'gr' | 'ti' | 'pi' | 'lu' | 'ci' | 'rx' | 'tfi' | 'lia' | 'custom';

// Lista de todos los iconos disponibles (basado en los archivos SVG en assets/icons)
export type IconName = 
  | 'accessibility'
  | 'accessible-icon-alt'
  | 'activity'
  | 'adjust-circle'
  | 'AI'
  | 'airplay'
  | 'alert-circle'
  | 'alert-octagon'
  | 'alert-triangle'
  | 'align-center'
  | 'align-justify'
  | 'align-left'
  | 'align-right'
  | 'anchor'
  | 'angry'
  | 'annoyed-alt'
  | 'annoyed'
  | 'aperture'
  | 'app-download'
  | 'archive'
  | 'arrow-down-circle'
  | 'arrow-down-left'
  | 'arrow-down-right'
  | 'arrow-down'
  | 'arrow-left-circle'
  | 'arrow-left'
  | 'arrow-right-circle'
  | 'arrow-right'
  | 'arrow-up-circle'
  | 'arrow-up-left'
  | 'arrow-up-right'
  | 'arrow-up'
  | 'arrows'
  | 'assistive-listening-systems'
  | 'at-sign'
  | 'award'
  | 'baby-carriage'
  | 'backpack'
  | 'balance-scale'
  | 'band-aid'
  | 'bar-chart-2'
  | 'bar-chart'
  | 'baseball-ball'
  | 'battery-charging'
  | 'battery'
  | 'beach'
  | 'bell-off'
  | 'bell'
  | 'bitcoin-circle'
  | 'bluetooth'
  | 'bold'
  | 'book-open'
  | 'book'
  | 'bookmark'
  | 'box'
  | 'brain'
  | 'briefcase'
  | 'brush-alt'
  | 'building'
  | 'bullet'
  | 'bus-1'
  | 'bus-alt'
  | 'bus-school'
  | 'bus'
  | 'buy-smart'
  | 'calculator'
  | 'calendar'
  | 'camera-off'
  | 'camera'
  | 'car-sideview'
  | 'car'
  | 'cast'
  | 'chart_data'
  | 'chart-arrow-1'
  | 'chart-arrow-2'
  | 'chart-arrow-3'
  | 'chart-arrow-4'
  | 'chart-arrow-5'
  | 'chart-bar'
  | 'chart-pie'
  | 'chat-bubble-user'
  | 'check-circle'
  | 'check-square'
  | 'check'
  | 'chef'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'chevrons-down'
  | 'chevrons-left'
  | 'chevrons-right'
  | 'chevrons-up'
  | 'chrome'
  | 'chronometer-180°'
  | 'chronometer-270°'
  | 'chronometer-320°'
  | 'chronometer-45°'
  | 'chronometer-90°'
  | 'circle'
  | 'clipboard'
  | 'clock'
  | 'cloud-drizzle'
  | 'cloud-lightning'
  | 'cloud-off'
  | 'cloud-rain'
  | 'cloud-snow'
  | 'cloud'
  | 'clouds'
  | 'club'
  | 'code'
  | 'codepen'
  | 'coffee'
  | 'coin-dollar'
  | 'coin-purse'
  | 'command'
  | 'comment-dots'
  | 'comment-exclamation'
  | 'comment-info'
  | 'comment-message'
  | 'comment-plus'
  | 'comment-question'
  | 'comment-verify'
  | 'comment'
  | 'company'
  | 'compass'
  | 'confused'
  | 'constructor'
  | 'copy'
  | 'corner-down-left'
  | 'corner-down-right'
  | 'corner-left-down'
  | 'corner-left-up'
  | 'corner-right-down'
  | 'corner-right-up'
  | 'corner-up-left'
  | 'corner-up-right'
  | 'cpu'
  | 'credit-card'
  | 'crop'
  | 'crosshair'
  | 'crutch'
  | 'currency_exchange'
  | 'Data-Seguridad'
  | 'database'
  | 'delete'
  | 'desert'
  | 'desktop'
  | 'disc'
  | 'discount'
  | 'doc'
  | 'dollar-sign'
  | 'download-cloud'
  | 'download'
  | 'droplet'
  | 'edit-2'
  | 'edit-3'
  | 'edit'
  | 'enough-coins'
  | 'euro-circle'
  | 'Excel'
  | 'external-link'
  | 'eye-off'
  | 'eye'
  | 'facebook'
  | 'fast-forward'
  | 'feather'
  | 'few-coins'
  | 'file-bill'
  | 'file-certificate'
  | 'file-chart-bars'
  | 'file-edit'
  | 'file-minus'
  | 'file-plus'
  | 'file-pointer'
  | 'file-text'
  | 'file-user'
  | 'file'
  | 'film'
  | 'filter'
  | 'first-page'
  | 'flag'
  | 'flower'
  | 'folder-minus'
  | 'folder-plus'
  | 'folder'
  | 'font-size'
  | 'football-american'
  | 'football-ball'
  | 'Gavel-judge'
  | 'gift'
  | 'git-branch'
  | 'git-commit'
  | 'git-merge'
  | 'git-pull-request'
  | 'github'
  | 'gitlab'
  | 'globe'
  | 'golf-ball'
  | 'grid'
  | 'grin'
  | 'Group 1707478416'
  | 'hand-money'
  | 'hard-drive'
  | 'hard-hat'
  | 'hash'
  | 'headphones'
  | 'headset'
  | 'heart-break'
  | 'heart'
  | 'help-circle'
  | 'history-alt'
  | 'history'
  | 'home'
  | 'hourglass'
  | 'Huella-Check'
  | 'Huella-error'
  | 'Huella-User'
  | 'Huella'
  | 'image-broken'
  | 'image'
  | 'inbox'
  | 'info'
  | 'invoice'
  | 'italic'
  | 'key'
  | 'kid'
  | 'lamp'
  | 'last-page'
  | 'laughing-1'
  | 'laughing'
  | 'layers'
  | 'layout'
  | 'life-buoy'
  | 'lifejacket'
  | 'line-height'
  | 'link-2'
  | 'link'
  | 'list'
  | 'loader'
  | 'lock'
  | 'log-in'
  | 'log-out-2'
  | 'log-out'
  | 'mail'
  | 'manteinance'
  | 'many-coins'
  | 'map-pin'
  | 'map'
  | 'mars'
  | 'maximize-2'
  | 'maximize'
  | 'meh'
  | 'menu'
  | 'message-circle'
  | 'message-info'
  | 'message-square'
  | 'message-talk'
  | 'messenger'
  | 'mic-off'
  | 'mic'
  | 'minimize-2'
  | 'minimize'
  | 'minus-circle'
  | 'minus-square'
  | 'minus'
  | 'monetization_on'
  | 'monetization'
  | 'money-bag'
  | 'money-change'
  | 'moon'
  | 'more-horizontal'
  | 'more-vertical'
  | 'mouse'
  | 'music'
  | 'navigation'
  | 'newspaper'
  | 'no-image'
  | 'notification'
  | 'octagon'
  | 'package'
  | 'paint-brush'
  | 'paper-plane'
  | 'pause'
  | 'pause-circle'
  | 'pen-tool'
  | 'phone'
  | 'phone-call'
  | 'phone-incoming'
  | 'phone-missed'
  | 'phone-off'
  | 'phone-outgoing'
  | 'pie-chart'
  | 'play'
  | 'play-circle'
  | 'plus'
  | 'plus-circle'
  | 'plus-square'
  | 'PowerPoint'
  | 'printer'
  | 'puzzle'
  | 'question-mark'
  | 'radio'
  | 'refresh'
  | 'repeat'
  | 'rewind'
  | 'rss'
  | 'save'
  | 'search'
  | 'send'
  | 'settings'
  | 'share'
  | 'shield'
  | 'shopping-bag'
  | 'shopping-cart'
  | 'shuffle'
  | 'skip-back'
  | 'skip-forward'
  | 'sliders'
  | 'smartphone'
  | 'smile'
  | 'smile-beam'
  | 'smile-wink'
  | 'sort'
  | 'speaker'
  | 'speaker-high'
  | 'speaker-low'
  | 'speaker-off'
  | 'square'
  | 'star'
  | 'star-half'
  | 'stop'
  | 'stop-circle'
  | 'sun'
  | 'sunrise'
  | 'sunset'
  | 'tablet'
  | 'tag'
  | 'target'
  | 'terminal'
  | 'thumbs-down'
  | 'thumbs-up'
  | 'toggle-left'
  | 'toggle-right'
  | 'trash'
  | 'trash-2'
  | 'trending-down'
  | 'trending-up'
  | 'trophy'
  | 'truck'
  | 'tv'
  | 'umbrella'
  | 'unlock'
  | 'upload'
  | 'user'
  | 'user-check'
  | 'user-minus'
  | 'user-plus'
  | 'user-x'
  | 'users'
  | 'video'
  | 'video-off'
  | 'volume-1'
  | 'volume-2'
  | 'volume-x'
  | 'watch'
  | 'wifi'
  | 'wifi-off'
  | 'wind'
  | 'Word'
  | 'x'
  | 'x-circle'
  | 'x-square'
  | 'zap'
  | 'zoom-in'
  | 'zoom-out';

const ICON_PREFIX_MAP: Record<string, IconSet> = {
  Hi: 'hi', // Heroicons
  Md: 'md', // Material Design
  Fa: 'fa', // Font Awesome
  Ri: 'ri', // Remix Icons
  Bi: 'bi', // Bootstrap Icons
  Ai: 'ai', // Ant Design Icons
  Bs: 'bs', // Bootstrap Icons
  Tb: 'tb', // Tabler Icons
  Gi: 'gi', // Game Icons
  Wi: 'wi', // Weather Icons
  Di: 'di', // Devicons
  Si: 'si', // Simple Icons
  Im: 'im', // IcoMoon Free
  Fi: 'fi', // Feather Icons
  Cg: 'cg', // CSS.gg
  Vsc: 'vsc', // VS Code Icons
  Go: 'go', // Github Octicons
  Gr: 'gr', // Grommet Icons
  Ti: 'ti', // Typicons
  Pi: 'pi', // Phosphor Icons
  Lu: 'lu', // Lucide Icons
  Ci: 'ci', // Circum Icons
  Rx: 'rx', // Radix Icons
  Tfi: 'tfi', // Themify Icons
  Lia: 'lia', // Line Awesome
};

const CUSTOM_ICONS = [
  'AI', 'Data-Seguridad', 'Excel', 'Gavel-judge', 'Huella-Check', 
  'Huella-User', 'Huella-error', 'Huella', 'Money-change', 'placeholder', 'PowerPoint',
  'Rostro', 'Torta-estadística', 'Vector-1', 'Vector', 'Word'
];

export const getIconSetFromName = (iconName: string): IconSet => {
  if (CUSTOM_ICONS.includes(iconName)) {
    return 'custom';
  }
  
  const prefix = iconName.substring(0, 2);
  return ICON_PREFIX_MAP[prefix] || 'fa';
};
